name: ✦ Barun's Contribution Engine

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  contribution-engine:
    name: ✦ Build Contribution Visualization
    runs-on: ubuntu-latest

    steps:
      - name: 🧬 Generate contribution map
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: b-a-r-u-n
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: ◈ Publish to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}